DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS sms_logs CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS message_threads CASCADE;
DROP TABLE IF EXISTS evaluation_versions CASCADE;
DROP TABLE IF EXISTS evaluations CASCADE;
DROP TABLE IF EXISTS evaluation_weeks CASCADE;
DROP TABLE IF EXISTS coach_student_assignments CASCADE;
DROP TABLE IF EXISTS coordinators CASCADE;
DROP TABLE IF EXISTS parents CASCADE;
DROP TABLE IF EXISTS coaches CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS registrations CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS sms_status;
DROP TYPE IF EXISTS thread_status;
DROP TYPE IF EXISTS thread_kind;
DROP TYPE IF EXISTS evaluation_status;
DROP TYPE IF EXISTS coach_status;
DROP TYPE IF EXISTS registration_kind;
DROP TYPE IF EXISTS registration_status;
DROP TYPE IF EXISTS user_role;

DROP FUNCTION IF EXISTS set_updated_at();
